### ISSUE TITLE
Board files don't match produced boards

### ISSUE THREAD

**Issue by ppannuto** [hamilton-mote/hw#2]
I've identified:
 - rightmost sensor as the HDC1080 (a "10")
 - upper right as the APDA-9007 (a "4")
 - left of the SAMR21 as the FXOS8700 (an "8")
 - just below the SAMR21 as the balun
 - top left of the SAMR21 as the crystal
 - and hiding at the top left of the board a AT30TS74 (a "1")

I don't know what I have, but it doesn't match the table for a 3C, so I have a (1+4+8+10)? 

![image](https://user-images.githubusercontent.com/339422/31323061-b26584cc-ac56-11e7-9b29-5efa58296823.png)

![img_0028](https://user-images.githubusercontent.com/339422/31323059-9f9d3bc8-ac56-11e7-98c1-fcefd9f5f673.jpg)

@Hyungsin this is going to be a problem for everyone trying to figure out what they need to power off if they can't figure out what's on the board -- @nealjack @adkinsjd and I struggled for half an hour to figure out what's going on and I think this is right?

**Comment by Hyungsin** [comment]
Hi Pat,

This is what you have.
I will announce it. Thanks.
Also, can you present two papers together on 10/19? Tock and Oppcast.

[image: Inline image 1]

-----------------------------------------------------------------------
*Hyung-Sin Kim*
Postdoctoral Researcher
Electrical Engineering and Computer Science
University of California, Berkeley
Homepage:
https://sites.google.com/site/netlabhome/people/alumni/hyung-sin-kim

**Comment by ppannuto** [comment]
Are the I/O connections correct?

What are the addresses of each sensor? The schematic in this repo doesn't even have the FXOS8700 in it at all.

**Comment by immesys** [comment]
Sorry, the files in here are for the Hamilton-7 (the one that actually really costs less than $10). I will consolidate the files for the 3C and 7C into this repo on Monday as well.

**Comment by immesys** [comment]
Also, you probably have a 3C. The chip you identified as a AT30TS74 is probably a TMP006

**Comment by immesys** [comment]
I moved the 3C hardware into this repo.
